# Generated by Django 4.2.2 on 2023-07-02 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_employee_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='image',
        ),
    ]
